version: '3'

services:
  joy_nginx:
    build:
      context: .
      dockerfile: components/docker/dockerfile/dockerfile_nginx
    ports:
      - '80:80'
    volumes:
      - ./components/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./entrypoint/api/attachments:/app/static/attachments:ro
      - ../frontend-admin/dist:/app/static/admin:ro
      - ../frontend-admin:/app/code/admin:delegated
    depends_on:
      - joy_server
  joy_server:
    build:
      context: .
      dockerfile: components/docker/dockerfile/dockerfile_php
    volumes:
      - ./:/app:delegated
      - ./components/docker/apache2/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./components/docker/apache2/mpm_prefork.conf:/etc/apache2/mods-available/mpm_prefork.conf
      - ./components/docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      - PHP_ENABLE_XDEBUG=1
      - XDEBUG_SESSION=1
      - PHP_IDE_CONFIG=serverName=docker_server
    depends_on:
      - joy_db
  joy_db:
    build:
      context: .
      dockerfile: components/docker/dockerfile/dockerfile_mysql
    platform: linux/x86_64 # закомментировать если выдает ошибку
    volumes:
      - ../db:/var/lib/mysql
      - ./components/docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '8100:3306'
