export const errors = {
  require: "Field is required",
  maxLength: "Maximum character count - ",
  maxPrice: "Maximum price - ",
  minPrice: "Minimum price - ",
  maxAmount: "Maximum amount - ",
  minAmount: "Minimum amount - ",
  minValue: "Minimum value - ",
  maxValue: "Maximum value - ",
  moreZero: "Value must be greater than 0",
  noSpecialSymbolsAllowed: "Special characters are not allowed",
  noSpecialFirstSymbolAllowed: "First symbol must be a letter or a quote",
  tooMuchAmount: "Must be less than the quantity of the product",

  errorEmail:
    "Invalid email or password. Check if everything is entered correctly",
  email: "Invalid email. Check if everything is entered correctly",
  passwordNoMatch: "Passwords do not match",
  noUser: "There is no user with this email",
  languageMax60: "Cyrillic, Latin, A-z, А-я, 0-9. Max 60 characters",
  maxValue255: "Maximum character count - 255",
  maxValue500: "Maximum character count - 500",
  maxValue1000: "Maximum character count - 1000",
  languageMax60MoreCharacters:
    " 'Cyrillic, Latin, -, «», \", A-z, А-я, 0-9. Max 60 characters'",
  password:
    "Latin, A-z, 0-9. Must contain an uppercase letter and a number. Min 8 - max 20 characters",
  errorNetwork: "Something went wrong, please try again later",
  noQuantityValue: "Field is required",
  minValue20: "Minimum character count - 20",
  imgPhoto: "An error occurred while trying to take a photo",
  imgGallery: "An error occurred while trying to upload an image",
  imgQuantity: "Minimum number of photos - 1",
  imgMax9: "Maximum number of photos - 9",
  imgMax5: "Maximum number of photos - 5",
  imgSize5: "Maximum allowed file size - 5MB",
  notValidEmail: "Invalid email. Check if everything is entered correctly",
  emailExists: "A user with this email already exists",
  wrongVerificationResetCode:
    "Invalid code entered. Check if everything is entered correctly",
  telephone: "A user with such a phone already exists",
  errorImage: "An error occurred when uploading images",
  errorPassword: "Invalid password. Check if everything is specified correctly",
  errorsPasswordMatches: "Passwords must not match",
  errorsOnboarding: "The maximum number of selected categories is 8",
  maxValue60: "The maximum number of characters is 60",
  notValidateTelephone: "Invalid phone number format",
  phoneUseAlready: "The phone number is already in use by another user",
  telegramMin5: "Minimum character count - 5",
  telegramMax32: "Maximum character count - 32",
};
