export const errors = {
  require: "此字段为必填项",
  maxLength: "最大字符数为",
  maxPrice: "最高价格为",
  minPrice: "最低价格是",
  maxAmount: "最低金额为",
  minAmount: "最高金额为",
  minValue: "最小值",
  maxValue: "最大值",
  moreZero: "值必须大于0",
  noSpecialSymbolsAllowed: "不允许使用特殊字符",
  noSpecialFirstSymbolAllowed: "第一个符号必须是字母或引号",
  tooMuchAmount: "必须小于产品的数量",

  errorEmail: "無效的電子郵件或密碼。 檢查所有內容是否輸入正確",
  email: "无效的电子邮件。请检查是否输入正确",
  passwordNoMatch: "密码不匹配",
  noUser: "此电子邮件没有用户",
  languageMax60: "西里尔字母，拉丁字母，A-z，А-я，0-9。最多60个字符",
  languageMax60MoreCharacters:
    " '西里尔字母，拉丁字母，-，«»，\"，A-z，А-я，0-9。最多60个字符'",
  password:
    "拉丁字母，A-z，0-9。必须包含大写字母和数字。最少8个字符 - 最多20个字符",
  errorNetwork: "出现错误，请稍后重试",
  noQuantityValue: "此字段为必填项",
  maxValue255: "最大字符数为255",
  maxValue60: "最大字符数为60",
  maxValue500: "最大字符数为500",
  maxValue1000: "最大字符数为1000",
  minValue20: "最小字符数为20",
  imgPhoto: "尝试拍照时发生错误",
  imgGallery: "尝试上传图像时发生错误",
  imgQuantity: "最少照片数量为1",
  imgMax9: "最多照片数量为9",
  imgMax5: "最多照片数量为5",
  imgSize5: "最大允许文件大小为5MB",
  notValidEmail: "无效的电子邮件。请检查是否输入正确",
  emailExists: "已存在该电子邮件的用户",
  wrongVerificationResetCode: "输入的代码有误。请检查是否输入正确",
  telephone: "拥有此类手机的用户已经存在",
  errorImage: "上传图片时出错",
  errorPassword: "密码无效。 检查是否正确指定了所有内容",
  errorsPasswordMatches: "密码不能匹配",
  errorsOnboarding: "所选类别的最大数量为8",
  notValidateTelephone: "电话号码格式无效",
  phoneUseAlready: "电话号码已被其他用户使用",
  telegramMin5: "最小字符数为5",
  telegramMax32: "最大字符数为32",
};
